version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: retro_reels_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retro_reels
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
